spring:
  application.name: ${artifactId}

info:
  app:
    name: ${spring.application.name}
    description: "Description"
    version: @project.version@
    artifactId: @project.artifactId@

server:
  # Authorization HTTP header requires to enlarge max header size.
  max-http-header-size: 65000

#set ( $dollar = "$")

---
spring:
  profiles: default

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${dollar}{eureka.uri:http://localhost:8761}/eureka/
      healthcheck:
        enabled: true

endpoints:
  health:
    sensitive: true

management:
  security:
    enabled: false
